// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {client} from '../models';
import {systemproxy} from '../models';
import {main} from '../models';

export function CheckBestProxy(arg1:number):Promise<Record<string, any>>;

export function CheckProxy(arg1:string,arg2:number):Promise<Record<string, any>>;

export function CheckRelayProfile(arg1:string):Promise<Record<string, any>>;

export function DeleteProxy(arg1:string):Promise<string>;

export function DeleteRelayProfile(arg1:string):Promise<string>;

export function DeleteSubscription(arg1:string):Promise<string>;

export function DisableSystemProxy():Promise<string>;

export function EnableSystemProxy():Promise<string>;

export function GetConfig():Promise<config.ClientConfig>;

export function GetLogs():Promise<Array<string>>;

export function GetRuntimeStatus():Promise<client.RuntimeStatus>;

export function GetState():Promise<Record<string, any>>;

export function GetSystemProxyStatus():Promise<systemproxy.Status>;

export function ImportProfiles(arg1:string,arg2:boolean,arg3:string):Promise<Array<any>>;

export function SaveConfig(arg1:config.ClientConfig):Promise<string>;

export function SaveRelayProfile(arg1:main.RelayProfileRequest):Promise<string>;

export function SaveSubscription(arg1:main.SubscriptionRequest):Promise<string>;

export function SelectProxy(arg1:string):Promise<string>;

export function SelectRelayProfile(arg1:string):Promise<string>;

export function Start():Promise<string>;

export function Stop():Promise<string>;

export function SyncSubscription(arg1:string,arg2:boolean):Promise<Array<any>>;
