// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckBestProxy(arg1) {
  return window['go']['main']['App']['CheckBestProxy'](arg1);
}

export function CheckProxy(arg1, arg2) {
  return window['go']['main']['App']['CheckProxy'](arg1, arg2);
}

export function CheckRelayProfile(arg1) {
  return window['go']['main']['App']['CheckRelayProfile'](arg1);
}

export function DeleteProxy(arg1) {
  return window['go']['main']['App']['DeleteProxy'](arg1);
}

export function DeleteRelayProfile(arg1) {
  return window['go']['main']['App']['DeleteRelayProfile'](arg1);
}

export function DeleteSubscription(arg1) {
  return window['go']['main']['App']['DeleteSubscription'](arg1);
}

export function DisableSystemProxy() {
  return window['go']['main']['App']['DisableSystemProxy']();
}

export function EnableSystemProxy() {
  return window['go']['main']['App']['EnableSystemProxy']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetRuntimeState() {
  return window['go']['main']['App']['GetRuntimeState']();
}

export function GetRuntimeStatus() {
  return window['go']['main']['App']['GetRuntimeStatus']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function GetSystemProxyStatus() {
  return window['go']['main']['App']['GetSystemProxyStatus']();
}

export function ImportProfiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportProfiles'](arg1, arg2, arg3);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveRelayProfile(arg1) {
  return window['go']['main']['App']['SaveRelayProfile'](arg1);
}

export function SaveSubscription(arg1) {
  return window['go']['main']['App']['SaveSubscription'](arg1);
}

export function SelectProxy(arg1) {
  return window['go']['main']['App']['SelectProxy'](arg1);
}

export function SelectRelayProfile(arg1) {
  return window['go']['main']['App']['SelectRelayProfile'](arg1);
}

export function Start() {
  return window['go']['main']['App']['Start']();
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}

export function SyncSubscription(arg1, arg2) {
  return window['go']['main']['App']['SyncSubscription'](arg1, arg2);
}
